version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"

  # Arduino Libraries
  # Since PlatformIO doesn't have direct Dependabot support,
  # we'll add a comment to remind users to manually check for updates
  # This is a placeholder and won't actually work automatically
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "platformio"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    commit-message:
      prefix: "pip"
      include: "scope"
