name: Code Quality

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cppcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install cppcheck
        run: sudo apt-get install -y cppcheck
        
      - name: Run cppcheck
        run: |
          cppcheck --enable=all --suppress=missingIncludeSystem --error-exitcode=1 src/ include/
          
  arduino_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Arduino Lint
        uses: arduino/arduino-lint-action@v2
        with:
          library-manager: update
          compliance: strict
          
  cpp_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Check C++ format with clang-format
        uses: jidicula/clang-format-action@v4.11.0
        with:
          clang-format-version: '14'
          check-path: 'src'
