name: Enforce Conventional Commits

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: Check Commit Messages
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Get all commits in the PR
            const { owner, repo } = context.repo;
            const { data: commits } = await github.rest.pulls.listCommits({
              owner,
              repo,
              pull_number: context.issue.number,
            });
            
            // Conventional commit regex pattern
            const conventionalPattern = /^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\(.+\))?: .{1,}/;
            
            // Check each commit message
            const invalidCommits = commits.filter(commit => {
              const message = commit.commit.message.split('\n')[0].trim();
              return !conventionalPattern.test(message);
            });
            
            if (invalidCommits.length > 0) {
              const invalidMessages = invalidCommits.map(commit => {
                const sha = commit.sha.substring(0, 7);
                const message = commit.commit.message.split('\n')[0].trim();
                return `- ${sha}: ${message}`;
              }).join('\n');
              
              core.setFailed(`
            The following commit messages do not follow the Conventional Commits format:
            ${invalidMessages}
            
            Please ensure your commits follow the format: type(scope): description
            
            Examples:
            - feat(wifi): add automatic reconnection feature
            - fix(http): resolve status endpoint JSON format error
            - docs(readme): update installation instructions
            
            For more details, see https://www.conventionalcommits.org/
            `);
            } else {
              console.log('All commit messages follow the Conventional Commits format! 👍');
            }
