name: Create Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e., v1.0, v20.15.10

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          
      - name: Install PlatformIO Core
        run: |
          python -m pip install --upgrade pip
          pip install platformio
          
      - name: Build firmware
        run: |
          pio run -e node32s
          
      - name: Generate version info
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.version.outputs.VERSION }}
          draft: false
          prerelease: false
          body: |
            ## ESP32 WiFi-Enabled Project ${{ steps.version.outputs.VERSION }}
            
            ### Changes in this release:
            - Please fill in manually
            
            ### Installation:
            1. Download the firmware.bin file
            2. Flash to your ESP32 using esptool or PlatformIO
            
            ### Requirements:
            - ESP32 NodeMCU or compatible board
            - External LED on GPIO4 (optional)
            
            ### Documentation:
            See README.md for complete details
      
      - name: Upload Firmware Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: .pio/build/node32s/firmware.bin
          asset_name: firmware-${{ steps.version.outputs.VERSION }}.bin
          asset_content_type: application/octet-stream
