name: PlatformIO CI

on:
  push:
    branches: [ "main", "master" ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    branches: [ "main", "master" ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Cache PlatformIO dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.platformio
          .pio
        key: ${{ runner.os }}-pio-${{ hashFiles('platformio.ini') }}
        restore-keys: |
          ${{ runner.os }}-pio-
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install PlatformIO Core
      run: |
        python -m pip install --upgrade pip
        pip install platformio
        pio platform update

    - name: Build ESP32 Project
      run: |
        pio run -e node32s
        
    - name: Archive firmware
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: |
          .pio/build/node32s/firmware.bin
          .pio/build/node32s/firmware.elf
        if-no-files-found: error

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install PlatformIO Core and cppcheck
      run: |
        python -m pip install --upgrade pip
        pip install platformio
        sudo apt-get update
        sudo apt-get install -y cppcheck
        
    - name: Run cppcheck
      run: |
        cppcheck --enable=all --error-exitcode=1 --suppress=missingIncludeSystem --suppress=unmatchedSuppression src/ include/
